[tool.poetry]
name = "supremo_lite"
version = "0.5.1"
description = "A lightweight memory first, model agnostic version of SuPreMo"
authors = ["Natalie Gill", "Sean Whalen"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
torch = ">=2.6"
pandas = "^2.2.3"
pyfaidx = "^0.8.1.3"


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"
pytest-cov = "^6.1.1"
black = "^25.1.0"
notebook = "^7.4.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
